export const initialState = {
  user: {
    id: 'usr_1811',
    name: 'Ravikant Upadhyay',
    email: 'nravikant123@gmail.com',
    role: 'Admin',
    timezone: 'Asia/Kolkata',
    language: 'English',
  },
  settings: {
    account: {
      name: 'Ravikant Upadhyay',
      email: 'nravikant123@gmail.com',
      timezone: 'Asia/Kolkata',
      language: 'English',
      avatarUrl: '',
    },
    smtp: {
      host: '',
      port: 587,
      user: '',
      pass: '',
      fromName: 'TraxQuickMail',
      replyTo: 'nravikant123@gmail.com',
    },
    domains: [
      { id: 'dom_1', domain: 'mail.company.com', dkim: true, spf: true, status: 'Verified' },
      { id: 'dom_2', domain: 'news.company.com', dkim: true, spf: false, status: 'Needs SPF' },
    ],
    integrations: [
      { id: 'int_1', name: 'Zapier', description: 'Connect with 5,000+ apps', status: 'Connected', color: '#FF4A00' },
      { id: 'int_2', name: 'Shopify', description: 'Sync your store data', status: 'Not Connected', color: '#96BF48' },
      { id: 'int_3', name: 'WordPress', description: 'Embed signup forms', status: 'Not Connected', color: '#21759B' },
      { id: 'int_4', name: 'HubSpot', description: 'CRM integration', status: 'Connected', color: '#FF7A59' },
      { id: 'int_5', name: 'Slack', description: 'Get campaign notifications', status: 'Connected', color: '#4A154B' },
    ],
    team: [
      { id: 'team_1', name: 'Sarah Johnson', email: 'sarah@company.com', role: 'Admin', status: 'Active' },
      { id: 'team_2', name: 'Michael Chen', email: 'michael@company.com', role: 'Editor', status: 'Active' },
      { id: 'team_3', name: 'Emma Williams', email: 'emma@company.com', role: 'Viewer', status: 'Active' },
    ],
    billing: {
      plan: 'Pro Plan',
      price: 99,
      period: 'month',
      sent: 248543,
      limit: 500000,
      renewalDate: 'May 24, 2026',
      invoices: [
        { id: 'inv_1', number: 'INV-2026-04', amount: 99, status: 'Paid', date: 'Apr 1, 2026' },
        { id: 'inv_2', number: 'INV-2026-03', amount: 99, status: 'Paid', date: 'Mar 1, 2026' },
      ],
    },
    notifications: [
      { id: 'ntf_1', label: 'Campaign sent', enabled: true },
      { id: 'ntf_2', label: 'Bounce detected', enabled: true },
      { id: 'ntf_3', label: 'New subscriber', enabled: false },
      { id: 'ntf_4', label: 'Automation completed', enabled: true },
    ],
  },
  campaigns: [
    {
      id: 'cmp_1',
      name: 'Spring Product Launch',
      status: 'Sent',
      subject: 'Introducing Our New Spring Collection',
      body: 'A polished product launch email for your audience.',
      segment: 'All Active Subscribers',
      sent: 45230,
      opens: 17288,
      clicks: 4116,
      openRate: 38.2,
      clickRate: 9.1,
      date: 'Apr 20, 2026',
      scheduledAt: '2026-04-20T09:00:00.000Z',
      revenue: 18240,
    },
    {
      id: 'cmp_2',
      name: 'Weekly Newsletter #247',
      status: 'Scheduled',
      subject: 'Your Weekly Roundup - Apr 26',
      body: 'A concise weekly roundup for engaged subscribers.',
      segment: 'Newsletter Subscribers',
      sent: 0,
      opens: 0,
      clicks: 0,
      openRate: 0,
      clickRate: 0,
      date: 'Apr 26, 2026',
      scheduledAt: '2026-04-26T09:00:00.000Z',
      revenue: 0,
    },
    {
      id: 'cmp_3',
      name: 'Re-engagement Campaign',
      status: 'Draft',
      subject: 'We Miss You! Come Back for 20% Off',
      body: 'A re-engagement message with a special offer.',
      segment: 'Inactive 90 Days',
      sent: 0,
      opens: 0,
      clicks: 0,
      openRate: 0,
      clickRate: 0,
      date: '-',
      scheduledAt: '',
      revenue: 0,
    },
    {
      id: 'cmp_4',
      name: 'Customer Feedback Survey',
      status: 'Sent',
      subject: 'Help Us Improve - Quick 2-Minute Survey',
      body: 'A short survey request for recent purchasers.',
      segment: 'Recent Purchasers',
      sent: 18450,
      opens: 7841,
      clicks: 2823,
      openRate: 42.5,
      clickRate: 15.3,
      date: 'Apr 18, 2026',
      scheduledAt: '2026-04-18T08:30:00.000Z',
      revenue: 5600,
    },
    {
      id: 'cmp_5',
      name: 'Flash Sale Alert',
      status: 'Paused',
      subject: '24-Hour Flash Sale - Up to 50% Off',
      body: 'A limited-time promotion with a clear CTA.',
      segment: 'High Engagement',
      sent: 12100,
      opens: 3473,
      clicks: 750,
      openRate: 28.7,
      clickRate: 6.2,
      date: 'Apr 15, 2026',
      scheduledAt: '2026-04-15T11:00:00.000Z',
      revenue: 4200,
    },
    {
      id: 'cmp_6',
      name: 'Abandoned Cart Recovery',
      status: 'Active',
      subject: 'You Left Something Behind...',
      body: 'An abandoned cart recovery email with urgency.',
      segment: 'Cart Abandoners',
      sent: 8945,
      opens: 3758,
      clicks: 1431,
      openRate: 42.0,
      clickRate: 16.0,
      date: 'Apr 22, 2026',
      scheduledAt: '2026-04-22T14:00:00.000Z',
      revenue: 9400,
    },
  ],
  automations: [
    {
      id: 'aut_1',
      name: 'Welcome Series',
      status: 'Active',
      trigger: 'Subscribed to list',
      enrolled: 1245,
      completed: 987,
      conversionRate: 23.4,
      nodes: 5,
      lastUpdated: 'Apr 21, 2026',
    },
    {
      id: 'aut_2',
      name: 'Abandoned Cart Recovery',
      status: 'Active',
      trigger: 'Cart abandoned',
      enrolled: 834,
      completed: 412,
      conversionRate: 18.7,
      nodes: 4,
      lastUpdated: 'Apr 20, 2026',
    },
    {
      id: 'aut_3',
      name: 'Re-engagement Campaign',
      status: 'Paused',
      trigger: 'No opens in 90 days',
      enrolled: 2341,
      completed: 1456,
      conversionRate: 8.2,
      nodes: 6,
      lastUpdated: 'Apr 18, 2026',
    },
    {
      id: 'aut_4',
      name: 'Birthday Campaign',
      status: 'Active',
      trigger: 'Birthday date',
      enrolled: 567,
      completed: 534,
      conversionRate: 31.2,
      nodes: 3,
      lastUpdated: 'Apr 22, 2026',
    },
  ],
  contacts: [
    {
      id: 'ct_1',
      name: 'Sarah Johnson',
      email: 'sarah.johnson@example.com',
      tags: ['VIP', 'Newsletter'],
      list: 'All Subscribers',
      lastActivity: '2 hours ago',
      openRate: 45.2,
      status: 'Active',
    },
    {
      id: 'ct_2',
      name: 'Michael Chen',
      email: 'michael.chen@example.com',
      tags: ['Customer'],
      list: 'Purchasers',
      lastActivity: '1 day ago',
      openRate: 62.1,
      status: 'Active',
    },
    {
      id: 'ct_3',
      name: 'Emma Williams',
      email: 'emma.w@example.com',
      tags: ['Newsletter', 'Engaged'],
      list: 'All Subscribers',
      lastActivity: '3 days ago',
      openRate: 38.7,
      status: 'Active',
    },
    {
      id: 'ct_4',
      name: 'James Rodriguez',
      email: 'james.r@example.com',
      tags: ['VIP', 'Customer'],
      list: 'Purchasers',
      lastActivity: '5 hours ago',
      openRate: 71.3,
      status: 'Active',
    },
    {
      id: 'ct_5',
      name: 'Lisa Anderson',
      email: 'lisa.anderson@example.com',
      tags: ['Newsletter'],
      list: 'All Subscribers',
      lastActivity: '2 weeks ago',
      openRate: 12.4,
      status: 'Inactive',
    },
    {
      id: 'ct_6',
      name: 'David Kim',
      email: 'david.kim@example.com',
      tags: ['Customer', 'Engaged'],
      list: 'Purchasers',
      lastActivity: '1 hour ago',
      openRate: 58.9,
      status: 'Active',
    },
  ],
  templates: [
    {
      id: 'tpl_1',
      name: 'Welcome Email',
      category: 'Welcome',
      preview: 'A warm welcome message for new subscribers',
      thumbnail: 'linear-gradient(135deg, #00D4AA 0%, #0EA5E9 100%)',
    },
    {
      id: 'tpl_2',
      name: 'Product Launch',
      category: 'Promotional',
      preview: 'Announce your latest product with style',
      thumbnail: 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)',
    },
    {
      id: 'tpl_3',
      name: 'Order Confirmation',
      category: 'Transactional',
      preview: 'Professional order receipt and details',
      thumbnail: 'linear-gradient(135deg, #3B82F6 0%, #8B5CF6 100%)',
    },
    {
      id: 'tpl_4',
      name: 'Weekly Newsletter',
      category: 'Newsletter',
      preview: 'Clean newsletter layout with content blocks',
      thumbnail: 'linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)',
    },
  ],
  scheduler: {
    view: 'month',
    timezone: 'UTC-7 (Pacific)',
    bestTime: [
      { day: 'Tuesday', time: '9:00 AM - 11:00 AM' },
      { day: 'Thursday', time: '2:00 PM - 4:00 PM' },
    ],
    events: [
      { id: 'sch_1', name: 'Weekly Newsletter #247', date: 'Apr 26, 2026', time: '09:00 AM', segment: 'Newsletter Subscribers', count: 32450, color: '#00D4AA', status: 'Scheduled' },
      { id: 'sch_2', name: 'Product Update', date: 'Apr 27, 2026', time: '02:00 PM', segment: 'All Active Users', count: 48230, color: '#8B5CF6', status: 'Scheduled' },
      { id: 'sch_3', name: 'Flash Sale Reminder', date: 'Apr 28, 2026', time: '10:30 AM', segment: 'High Engagement', count: 12100, color: '#F5A623', status: 'Scheduled' },
      { id: 'sch_4', name: 'Monthly Roundup', date: 'May 1, 2026', time: '08:00 AM', segment: 'All Subscribers', count: 54300, color: '#3B82F6', status: 'Scheduled' },
    ],
    calendar: [
      { day: 24, month: 'current', events: [{ name: 'Today', color: '#00D4AA' }] },
      { day: 26, month: 'current', events: [{ name: 'Weekly Newsletter', color: '#00D4AA' }] },
      { day: 27, month: 'current', events: [{ name: 'Product Update', color: '#8B5CF6' }] },
      { day: 28, month: 'current', events: [{ name: 'Flash Sale', color: '#F5A623' }] },
      { day: 1, month: 'next', events: [{ name: 'Monthly Roundup', color: '#3B82F6' }] },
    ],
  },
  analytics: {
    performanceData: [
      { month: 'Jan', opens: 28000, clicks: 8400, conversions: 1680 },
      { month: 'Feb', opens: 32000, clicks: 9600, conversions: 1920 },
      { month: 'Mar', opens: 35000, clicks: 10500, conversions: 2100 },
      { month: 'Apr', opens: 38000, clicks: 11400, conversions: 2280 },
    ],
    deviceData: [
      { name: 'Desktop', value: 45, color: '#00D4AA' },
      { name: 'Mobile', value: 42, color: '#8B5CF6' },
      { name: 'Tablet', value: 13, color: '#F5A623' },
    ],
    topCampaigns: [],
  },
  dashboard: {
    kpis: [
      {
        id: 'total-sent',
        label: 'Total Sent',
        value: '248,543',
        change: '+12.5%',
        trend: 'up',
        sparklineData: [
          { value: 30 },
          { value: 45 },
          { value: 38 },
          { value: 52 },
          { value: 48 },
          { value: 65 },
          { value: 72 },
        ],
      },
      {
        id: 'open-rate',
        label: 'Open Rate',
        value: '34.2%',
        change: '+3.8%',
        trend: 'up',
        sparklineData: [
          { value: 28 },
          { value: 32 },
          { value: 30 },
          { value: 35 },
          { value: 33 },
          { value: 36 },
          { value: 34 },
        ],
      },
      {
        id: 'click-rate',
        label: 'Click Rate',
        value: '8.7%',
        change: '+1.2%',
        trend: 'up',
        sparklineData: [
          { value: 6 },
          { value: 7 },
          { value: 8 },
          { value: 7.5 },
          { value: 8.2 },
          { value: 8.5 },
          { value: 8.7 },
        ],
      },
      {
        id: 'unsubscribes',
        label: 'Unsubscribes',
        value: '342',
        change: '-2.1%',
        trend: 'down',
        sparklineData: [
          { value: 15 },
          { value: 12 },
          { value: 18 },
          { value: 14 },
          { value: 13 },
          { value: 11 },
          { value: 10 },
        ],
      },
      {
        id: 'revenue',
        label: 'Revenue Attributed',
        value: '$127,450',
        change: '+24.3%',
        trend: 'up',
        sparklineData: [
          { value: 80 },
          { value: 90 },
          { value: 85 },
          { value: 100 },
          { value: 110 },
          { value: 120 },
          { value: 127 },
        ],
      },
    ],
    audience30: [
      { date: 'Mar 25', subscribers: 42000 },
      { date: 'Mar 28', subscribers: 43200 },
      { date: 'Apr 1', subscribers: 44500 },
      { date: 'Apr 5', subscribers: 46800 },
      { date: 'Apr 10', subscribers: 48200 },
      { date: 'Apr 15', subscribers: 50100 },
      { date: 'Apr 20', subscribers: 52400 },
      { date: 'Apr 24', subscribers: 54300 },
    ],
    audience60: [
      { date: 'Feb 24', subscribers: 35000 },
      { date: 'Mar 5', subscribers: 37200 },
      { date: 'Mar 15', subscribers: 39800 },
      { date: 'Mar 25', subscribers: 42000 },
      { date: 'Apr 5', subscribers: 46800 },
      { date: 'Apr 15', subscribers: 50100 },
      { date: 'Apr 24', subscribers: 54300 },
    ],
    audience90: [
      { date: 'Jan 24', subscribers: 28000 },
      { date: 'Feb 10', subscribers: 32000 },
      { date: 'Feb 25', subscribers: 36500 },
      { date: 'Mar 12', subscribers: 40200 },
      { date: 'Mar 28', subscribers: 45000 },
      { date: 'Apr 12', subscribers: 49800 },
      { date: 'Apr 24', subscribers: 54300 },
    ],
  },
};
